"""리뷰 결과 → Markdown / TXT / DOCX (DOCX 는 stdlib zipfile 로 직접 쓴다 — python-docx 불필요)"""
import datetime
import io
import re
import zipfile
from xml.sax.saxutils import escape

L = {
    "ko": {"title": "투고 전 사전 심사 리뷰", "file": "파일", "date": "일시", "model": "모델", "journal": "대상 저널·분야", "type": "원고 유형",
           "depth": "리뷰 깊이", "note": "로컬 LLM 과 규칙 점검으로 만든 참고용 리뷰입니다. 인용·위치는 원고에서 자동 확인했지만, 판단은 저자가 검토하세요. 원고는 이 서버 밖으로 나가지 않았습니다.",
           "summary": "원고가 주장하는 기여", "verdict": "예상 판정", "major": "주요 지적 (Major)", "minor": "세부 지적 (Minor)",
           "rule": "기계적 점검 (규칙 기반)", "questions": "예상 심사위원 질문", "why": "문제", "fix": "수정", "tip": "답변 준비",
           "where": "위치", "none": "없음", "info": "참고", "nollm": "(LLM 리뷰를 아직 실행하지 않았습니다 — 기계적 점검 결과만 있습니다)"},
    "en": {"title": "Pre-submission Review", "file": "File", "date": "Date", "model": "Model", "journal": "Target journal / field", "type": "Manuscript type",
           "depth": "Depth", "note": "Advisory review generated by a local LLM plus rule-based checks. Quotes and locations were verified against the manuscript automatically; judge each point yourself. The manuscript never left this server.",
           "summary": "Claimed contributions", "verdict": "Expected decision", "major": "Major comments", "minor": "Minor comments",
           "rule": "Mechanical checks (rule-based)", "questions": "Questions a reviewer is likely to ask", "why": "Issue", "fix": "Suggested fix", "tip": "How to prepare",
           "where": "Location", "none": "None", "info": "Note", "nollm": "(LLM review not run yet — mechanical checks only)"},
}
SEV_ORDER = {"major": 0, "minor": 1, "info": 2}


def _lab(rec):
    return L["en" if (rec.get("review") or {}).get("lang") == "en" else "ko"]


def sections(rec):
    """공통 구조: [(kind, payload)] — md/txt/docx 가 같은 내용을 쓴다"""
    lab, doc, rv = _lab(rec), rec["doc"], rec.get("review") or {}
    opt = rv.get("options") or rec.get("options") or {}
    out = [("h1", f"{lab['title']} — {doc.get('title') or doc.get('name')}"),
           ("meta", [(lab["file"], doc.get("name", "")), (lab["date"], rv.get("ts") or rec.get("ts", "")), (lab["model"], rv.get("model", "")),
                     (lab["journal"], opt.get("journal") or "-"), (lab["type"], opt.get("mtype") or "-"), (lab["depth"], opt.get("depth") or "-")]),
           ("note", lab["note"])]
    if not rv:
        out.append(("p", lab["nollm"]))
    else:
        out.append(("h2", lab["summary"]))
        out.append(("ol", rv.get("summary", {}).get("contrib") or [lab["none"]]))
        v = rv.get("verdict") or {}
        out.append(("h2", f"{lab['verdict']}: {v.get('label') or '-'}"))
        out.append(("ul", [r["text"] for r in v.get("reasons") or []]))
    issues = rec.get("issues") or []
    llm = [i for i in issues if i["src"] == "llm"]
    for sev, key in (("major", "major"), ("minor", "minor")):
        if not rv:
            break
        items = [i for i in llm if i["sev"] == sev]
        out.append(("h2", lab[key]))
        if not items:
            out.append(("p", lab["none"]))
        for i in items:
            out.append(("issue", i))
    rule = sorted([i for i in issues if i["src"] == "rule"], key=lambda i: (SEV_ORDER.get(i["sev"], 3), i["cat"], i["pos"]))
    out.append(("h2", lab["rule"]))
    if not rule:
        out.append(("p", lab["none"]))
    for i in rule:
        out.append(("rule", i))
    if rv and rv.get("questions"):
        out.append(("h2", lab["questions"]))
        out.append(("qa", rv["questions"]))
    return out, lab


def to_md(rec):
    secs, lab = sections(rec)
    o = []
    for kind, x in secs:
        if kind == "h1":
            o.append(f"# {x}\n")
        elif kind == "h2":
            o.append(f"\n## {x}\n")
        elif kind == "meta":
            o += [f"- **{k}**: {v}" for k, v in x if v]
        elif kind == "note":
            o.append(f"\n> {x}\n")
        elif kind == "p":
            o.append(x)
        elif kind == "ol":
            o += [f"{n}. {t}" for n, t in enumerate(x, 1)]
        elif kind == "ul":
            o += [f"- {t}" for t in x]
        elif kind == "issue":
            o.append(f"### {x['id']}. {x.get('title') or x['cat']}  `{x['cat']}`")
            o.append(f"*{lab['where']}: {x.get('where') or '-'}" + "".join(f" · {a['where']}" for a in x.get("also") or []) + "*\n")
            if x.get("quote"):
                o.append(f"> {x['quote']}\n")
            o.append(f"- **{lab['why']}**: {x['why']}")
            if x.get("fix"):
                o.append(f"- **{lab['fix']}**: {x['fix']}")
            o.append("")
        elif kind == "rule":
            tag = {"major": "**[major]** ", "minor": "", "info": f"[{lab['info']}] "}.get(x["sev"], "")
            o.append(f"- {tag}**{x['title']}** ({x.get('where') or '-'}) — {x['why']}" + (f" → {x['fix']}" if x.get("fix") else ""))
            if x.get("quote"):
                o.append(f"  > {x['quote'][:220]}")
        elif kind == "qa":
            for n, q in enumerate(x, 1):
                o.append(f"{n}. **{q['q']}**")
                if q.get("tip"):
                    o.append(f"   - {lab['tip']}: {q['tip']}")
    return "\n".join(o).strip() + "\n"


def to_txt(rec):
    md = to_md(rec)
    md = re.sub(r"^#+\s*", "", md, flags=re.M)
    md = re.sub(r"\*\*(.+?)\*\*", r"\1", md)
    md = re.sub(r"(?<!\w)\*(.+?)\*(?!\w)", r"\1", md)
    return md.replace("`", "")


# ── DOCX ────────────────────────────────────────────────────────────────
CT = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.styles+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/></Types>"""
RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/></Relationships>"""
DOC_RELS = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>"""
FONT = '<w:rFonts w:ascii="Calibri" w:hAnsi="Calibri" w:eastAsia="맑은 고딕" w:cs="Calibri"/>'
STYLES = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:styles xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
<w:docDefaults><w:rPrDefault><w:rPr>{FONT}<w:sz w:val="21"/><w:lang w:val="ko-KR" w:eastAsia="ko-KR"/></w:rPr></w:rPrDefault><w:pPrDefault><w:pPr><w:spacing w:after="80" w:line="276" w:lineRule="auto"/></w:pPr></w:pPrDefault></w:docDefaults>
<w:style w:type="paragraph" w:default="1" w:styleId="Normal"><w:name w:val="Normal"/></w:style>
<w:style w:type="paragraph" w:styleId="Title"><w:name w:val="Title"/><w:basedOn w:val="Normal"/><w:pPr><w:spacing w:after="160"/></w:pPr><w:rPr><w:b/><w:sz w:val="32"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Heading1"><w:name w:val="heading 1"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/><w:pPr><w:keepNext/><w:spacing w:before="280" w:after="100"/><w:outlineLvl w:val="0"/></w:pPr><w:rPr><w:b/><w:color w:val="1F3A93"/><w:sz w:val="26"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Heading2"><w:name w:val="heading 2"/><w:basedOn w:val="Normal"/><w:next w:val="Normal"/><w:pPr><w:keepNext/><w:spacing w:before="180" w:after="60"/><w:outlineLvl w:val="1"/></w:pPr><w:rPr><w:b/><w:sz w:val="22"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Quote"><w:name w:val="Quote"/><w:basedOn w:val="Normal"/><w:pPr><w:pBdr><w:left w:val="single" w:sz="12" w:space="6" w:color="B0B7C3"/></w:pBdr><w:ind w:left="240"/></w:pPr><w:rPr><w:i/><w:color w:val="404854"/></w:rPr></w:style>
<w:style w:type="paragraph" w:styleId="Note"><w:name w:val="Note"/><w:basedOn w:val="Normal"/><w:rPr><w:color w:val="6B7280"/><w:sz w:val="18"/></w:rPr></w:style>
</w:styles>"""


def _run(text, b=False, i=False, color=None):
    rpr = ("<w:b/>" if b else "") + ("<w:i/>" if i else "") + (f'<w:color w:val="{color}"/>' if color else "")
    return f'<w:r>{"<w:rPr>" + rpr + "</w:rPr>" if rpr else ""}<w:t xml:space="preserve">{escape(text)}</w:t></w:r>'


def _p(runs, style=None, ind=0):
    ppr = (f'<w:pStyle w:val="{style}"/>' if style else "") + (f'<w:ind w:left="{ind}"/>' if ind else "")
    if isinstance(runs, str):
        runs = _run(runs)
    return f'<w:p>{"<w:pPr>" + ppr + "</w:pPr>" if ppr else ""}{runs}</w:p>'


def to_docx(rec):
    secs, lab = sections(rec)
    body = []
    for kind, x in secs:
        if kind == "h1":
            body.append(_p(x, "Title"))
        elif kind == "h2":
            body.append(_p(x, "Heading1"))
        elif kind == "meta":
            body += [_p(_run(f"{k}: ", b=True) + _run(str(v))) for k, v in x if v]
        elif kind == "note":
            body.append(_p(x, "Note"))
        elif kind == "p":
            body.append(_p(x))
        elif kind in ("ol", "ul"):
            body += [_p(f"{n}. {t}" if kind == "ol" else f"• {t}", ind=240) for n, t in enumerate(x, 1)]
        elif kind == "issue":
            body.append(_p(f"{x['id']}. {x.get('title') or x['cat']}  [{x['cat']}]", "Heading2"))
            body.append(_p(_run(f"{lab['where']}: {x.get('where') or '-'}" + "".join(f" · {a['where']}" for a in x.get("also") or []), i=True, color="6B7280")))
            if x.get("quote"):
                body.append(_p(x["quote"], "Quote"))
            body.append(_p(_run(f"{lab['why']}: ", b=True) + _run(x["why"])))
            if x.get("fix"):
                body.append(_p(_run(f"{lab['fix']}: ", b=True) + _run(x["fix"])))
        elif kind == "rule":
            col = {"major": "B42318", "info": "6B7280"}.get(x["sev"])
            body.append(_p(_run(f"• {x['title']} ", b=True, color=col) + _run(f"({x.get('where') or '-'}) — {x['why']}" + (f" → {x['fix']}" if x.get("fix") else "")), ind=120))
            if x.get("quote"):
                body.append(_p(x["quote"][:220], "Quote"))
        elif kind == "qa":
            for n, q in enumerate(x, 1):
                body.append(_p(_run(f"{n}. {q['q']}", b=True)))
                if q.get("tip"):
                    body.append(_p(_run(f"{lab['tip']}: ", i=True) + _run(q["tip"]), ind=240))
    doc = ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
           f'<w:body>{"".join(body)}<w:sectPr><w:pgSz w:w="11906" w:h="16838"/><w:pgMar w:top="1300" w:right="1200" w:bottom="1300" w:left="1200" w:header="600" w:footer="600" w:gutter="0"/></w:sectPr></w:body></w:document>')
    now = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    core = ('<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" '
            'xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dcterms="http://purl.org/dc/terms/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">'
            f'<dc:title>{escape(lab["title"])}</dc:title><dc:creator>review-local</dc:creator>'
            f'<dcterms:created xsi:type="dcterms:W3CDTF">{now}</dcterms:created></cp:coreProperties>')
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("[Content_Types].xml", CT)
        z.writestr("_rels/.rels", RELS)
        z.writestr("word/_rels/document.xml.rels", DOC_RELS)
        z.writestr("word/document.xml", doc)
        z.writestr("word/styles.xml", STYLES)
        z.writestr("docProps/core.xml", core)
    return buf.getvalue()
